description "Resonator"

subprojects {
    apply plugin: "java-library"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/apache-snapshots' }
        mavenCentral()
        mavenLocal()
    }


    jar {
        setDuplicatesStrategy DuplicatesStrategy.INCLUDE
        from rootProject.file('LICENSE')
    }


    test {
        useJUnitPlatform()
    }

    dependencies {
    }

    javadoc.options.encoding = 'UTF-8'

    tasks.withType(JavaCompile).configureEach {
        options.encoding 'UTF-8'
    }

    tasks.withType(GroovyCompile).configureEach {
        options.encoding 'UTF-8'
    }
}
