description "Resonator"

subprojects {
  apply plugin: "java-library"

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(17)
    }
  }

  repositories {
    mavenCentral()
    mavenLocal()
  }


  jar {
    setDuplicatesStrategy DuplicatesStrategy.INCLUDE
    from rootProject.file('LICENSE')
  }


  test {
    useJUnitPlatform()
  }

  dependencies {
    implementation 'com.google.guava:guava:33.3.1-jre'
  }

  javadoc.options.encoding = 'UTF-8'

  tasks.withType(JavaCompile).configureEach {
    options.encoding 'UTF-8'
  }

  tasks.withType(GroovyCompile).configureEach {
    options.encoding 'UTF-8'
  }
}
