org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true
org.gradle.daemon=true
java_version=21
slf4j_version=2.0.9
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
junit_jupiter_version=5.11.3
# https://mvnrepository.com/artifact/com.google.guava/guava
guava_version=33.2.1
java_semver_version=0.10.2
gson_version=2.10.1
jsr305_version=3.0.2
